
name: 'certificacao_fea'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuração dos modelos
models:
  certificacao_fea:

    # Unity Catalog
    +catalog: fea_academy

    # Schema de escrita
    #+schema: certificacao_fea

    # Camada Staging
    staging:
      +materialized: view
      +tags: ["staging"]

      person:
        +tags: ["person"]

      production:
        +tags: ["production"]

      purchasing:
        +tags: ["purchasing"]

      sales:
        +tags: ["sales"]

    # Camada Intermediate
    intermediate:
      +materialized: view
      +tags: ["intermediate"]

      bridges:
        +tags: ["bridge"]

      dimensions:
        +tags: ["dimension"]

      facts:
        +tags: ["fact"]

    # Camada Mart
    marts:
      +materialized: view
      +tags: ["mart"]

      bridges:
        +tags: ["bridge"]

      dimensions:
        +tags: ["dimension"]

      facts:
        +tags: ["fact"]